spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customer/**

        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/api/v1/order/**

        - id: product
          uri: lb://product
          predicates:
            - Path=/api/v1/products/**

        - id: payment
          uri: lb://PAYMENT
          predicates:
            - Path=/api/v1/payment/**
server:
  port: 8222




